project_name: cartpole
experiment: exp 
seed: 42
model:
  type: ffn
  input_size: 4 
  dropout: 0.2 

training: 
  learning_rate: 0.001 
  batch_size: 32 
  epochs: 20 
  optimizer: adam 
  
  # rl specific
  n_episodes: 20000 # 100_000
  start_epsilon: 1.0
  final_epsilon: 0.1
  max_episode_steps: 500 
  discount_factor: 0.95

  checkpoint_interval: 1000
  target_update_freq: 500  
  continue_train: False # resume training from the last checkpoint 

data: 
  dataset: ""

device: "cuda:0" # auto chooses GPU is available 